@echo off
rem (2026-07-13) Safe pull script with stash protect; was no pull script
echo [1/3] Stashing local changes...
git stash
echo [2/3] Pulling latest changes from origin main...
git pull origin main
echo [3/3] Restoring stashed changes...
git stash pop
